### ISSUE TITLE
Configurar GitHub Pages para releases

### ISSUE THREAD

**Issue by codediaz** [gdgecuador/landing-gdggye#10]
# Objetivo
Configurar un flujo de trabajo de GitHub Actions para desplegar automáticamente nuestro proyecto a GitHub Pages cuando se cree una nueva rama de release.

## Tareas
- [ ] Crear un nuevo archivo de flujo de trabajo de GitHub Actions (`.github/workflows/deploy-release.yml`)
- [ ] Configurar el trigger para que se ejecute en pushes a ramas que coincidan con el patrón `release/*`
- [ ] Implementar los pasos del flujo de trabajo para construir y desplegar el proyecto
- [ ] Verificar que el despliegue funcione correctamente en un entorno de prueba
- [ ] Actualizar la documentación del proyecto con información sobre el proceso de despliegue

## Configuración propuesta del flujo de trabajo
```yaml
name: Deploy Release to GitHub Pages

on:
  push:
    branches: ["release/*"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist  # Ajustar según la carpeta de salida de tu build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

## Consideraciones adicionales
- Asegurarse de que el repositorio tenga habilitado GitHub Pages
- Verificar que las credenciales y permisos estén correctamente configurados
- Ajustar la configuración según las necesidades específicas del proyecto (por ejemplo, comandos de build personalizados)
- Considerar la adición de pasos de prueba antes del despliegue

## Notas
- Este flujo de trabajo se activará automáticamente cuando se cree una nueva rama de release (por ejemplo, `release/1.0.0`)
- El despliegue creará una nueva versión del sitio en GitHub Pages, permitiendo una vista previa antes de fusionar en la rama principal

## Recursos
- [Documentación de GitHub Actions](https://docs.github.com/en/actions)
- [Configuración de GitHub Pages](https://docs.github.com/en/pages)
